version: "3.8"

services:
  app:
    build: .
    container_name: server_monitoring_app
    restart: always
    ports:
      - "3000:3000"
      - "1883:1883"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=absensi_user
      - DB_PASSWORD=absensi_password
      - DB_NAME=db_absensi
      # Add other environment variables from .env here if needed
      - OWNCLOUD_URL=${OWNCLOUD_URL}
      - OWNCLOUD_USERNAME=${OWNCLOUD_USERNAME}
      - OWNCLOUD_PASSWORD=${OWNCLOUD_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - absensi_net

  postgres:
    image: postgres:15-alpine
    container_name: postgres_absensi
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_USER: absensi_user
      POSTGRES_PASSWORD: absensi_password
      POSTGRES_DB: db_absensi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /tmp:mode=1777,size=64M
      - /run:mode=1777,size=64M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U absensi_user -d db_absensi"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - absensi_net

volumes:
  postgres_data:
    driver: local

networks:
  absensi_net:
    driver: bridge
