version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_absensi
    restart: always
    environment:
      POSTGRES_USER: absensi_user
      POSTGRES_PASSWORD: absensi_password
      POSTGRES_DB: db_absensi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_postgresql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U absensi_user -d db_absensi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
